name: "Build Typedoc Documentation"
description: "Checks out code, installs dependencies, and runs the documentation build command."

runs:
  using: "composite" # 👈 Defines this as a Composite Action
  steps:
    # NOTE: We keep the checkout here because the action needs the code to run npm install/build
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Npm install
      run: npm ci --ignore-scripts
      shell: bash
    - name: Enforce Typedoc Config from Action
      shell: bash
      # Copies the typedoc.json from the action folder ($GITHUB_ACTION_PATH)
      # to the root of the project's working directory ($GITHUB_WORKSPACE),
      # overwriting any existing file.
      run: cp "$GITHUB_ACTION_PATH/typedoc.json" "$GITHUB_WORKSPACE/typedoc.json"

    - name: Build doc (Run typedoc)
      shell: bash
      # Since the enforced file is now in the default location (typedoc.json in CWD),
      # we can run the command simply, letting TypeDoc find it naturally.
      # You can even revert to 'npm run generate:code-docs' if that script just calls `typedoc`.
      run: npx typedoc
