name: "Publish Documentation"

on:
  workflow_call:
    inputs:
      bot_id:
        description: "The Bot ID for authentication"
        required: true
        type: string
      bot_sk:
        description: "The Bot Secret Key for authentication"
        required: true
        type: string
      artifact_path:
        description: "The path to the documentation artifact to publish"
        required: true
        type: string

jobs:
  publish-docs-to-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout source code (required for artifact/code access)
        uses: actions/checkout@v4

      # 🚨 Call the new publishing Composite Action
      - name: Deploy Documentation to Pages
        uses: p2arthur/reusable-workflows/.github/actions/publish-docs@main
        with:
          bot_id: ${{ inputs.bot_id }}
          bot_sk: ${{ inputs.bot_sk }}
          artifact_path: docs/_html # Pass the specific path created by the build step
