name: "Publish Documentation"

on:
  workflow_call:
    secrets:
      BOT_SK:
        required: true
      BOT_ID:
        required: true

jobs:
  publish-docs-to-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout source code (required for artifact/code access)
        uses: actions/checkout@v4

      # NOTE: INSERT YOUR BUILD STEP HERE (e.g., the generate-docs Composite Action)
      # - name: Build Documentation
      #   uses: p2arthur/reusable-workflows/.github/actions/generate-docs@main
      # -----------------------------------------------------------------------

      # 🚨 Call the new publishing Composite Action
      - name: Deploy Documentation to Pages
        uses: p2arthur/reusable-workflows/.github/actions/publish-docs@main
        with:
          bot_id: ${{ inputs.bot_id }}
          bot_sk: ${{ inputs.bot_sk }}
          artifact_path: docs/_html # Pass the specific path created by the build step
